# Generated by Django 3.2.2 on 2021-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
