# Generated by Django 3.2.2 on 2021-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
