# Generated by Django 3.2.2 on 2021-05-10 13:56

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=32, null=True)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
