# Generated by Django 3.2.2 on 2021-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0006_auto_20210510_0700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
